### PR TITLE
Epitools, draft of PR

### PR DESCRIPTION
**Pull request by NicoRicardi**
## Description

All functions reproduce the results from the R implementation. I can make tests quite quickly.
Still, a lot of functions are not implemented yet.

For docstring and documentation, should we write a detailed one or refer to the R docs?
I feel like the former would be a lot of work because of how bare-bon the R docs are

### CODE REVIEW

**Comment by fccoelho** [comment]
@NicoRicardi please add unit tests for these functions

**Comment by fccoelho** [comment]
thanks  @NicoRicardi ! I'll review it ASAP.

**Comment by fccoelho** [comment]
@eduardocorrearaujo Could you take over this PR? There is no need to implement new things, just to address the comments I made to the codebase and turn this into a usable module, even though it may be incomplete compared to R Epitools, for now.

**Comment by eduardocorrearaujo** [comment]
> @eduardocorrearaujo Could you take over this PR? There is no need to implement new things, just to address the comments I made to the codebase and turn this into a usable module, even though it may be incomplete compared to R Epitools, for now.

Yes, I will look at it at the weekend.

**Pull request closed without merging**
