### PR TITLE
chore(deps): Fix dependencies

### PR DESCRIPTION
**Pull request by xmnlab**
## Checklist

- [ ] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/thegraphnetwork/epigraphhub_py/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I've read the [`CONTRIBUTING.md`](https://github.com/thegraphnetwork/epigraphhub_py/blob/master/CONTRIBUTING.md) guide.
- [ ] I've used pre-commit hook locally.
- [ ] I've written tests for all new methods and classes that I created.
- [ ] I've written the docstring in Google format for all the methods and classes that I used.
- [ ] Semantic-release prefix title used (case sensitive):
  - Use the prefix `chore(docs):` for Examples / docs / tutorials / dependencies update
  - Use the prefix `fix:` for a bug fix
    (non-breaking change which fixes an issue).
  - Use the prefix `chore(improvement):` for an improvement
    (non-breaking change which improves an existing feature).
  - Use the prefix `feat:` for a new feature
    (non-breaking change which adds functionality).
  - Use the prefix `BREAKING CHANGE:` for a breaking change
    (fix or feature that would cause existing functionality to change).
  - Use the prefix `chore(security):` for a security fix.

**Note**: The title prefix can be also expanded with more information
inside the parenthesis. Some examples for a full title (prefix + message):
- `fix(login): Fix the login page`.
- `feat(forecast): Add a weather forecast page`.
- `chore(security-login): Add a weather forecast page`.

### CODE REVIEW

**Comment by xmnlab** [comment]
@fccoelho  the unit tests on CI is silently failing:

```
=========================== short test summary info ============================
FAILED tests/test_analysis/test_ngboost_models.py::test_rolling_predictions - TypeError: interval() got an unexpected keyword argument 'alpha'
FAILED tests/test_analysis/test_ngboost_models.py::test_rolling_forecast - TypeError: interval() got an unexpected keyword argument 'alpha'
FAILED tests/test_data/test_foph.py::test_downloading_daily_csv_cases - pandas.errors.EmptyDataError: No columns to parse from file
FAILED tests/test_data/test_foph.py::test_downloading_weekly_csv_default_cases - pandas.errors.EmptyDataError: No columns to parse from file
FAILED tests/test_data/test_foph.py::test_downloading_weekly_csv_by_age_cases - pandas.errors.EmptyDataError: No columns to parse from file
FAILED tests/test_data/test_foph.py::test_downloading_weekly_csv_by_sex_cases - pandas.errors.EmptyDataError: No columns to parse from file
===== 6 failed, 38 passed, 17 skipped, 3973 warnings in 197.93s (0:03:17) ======
```

I am not sure about the error about the interval ... I tried to find the interval function in scikit learn and ngboos .. but I didn't have any success.

let me know if it would be ok to move forward with this PR or if you want any change.

**Comment by xmnlab** [comment]
@fccoelho , a friendly reminder about this PR, thanks!

**Review by fccoelho — APPROVED** [review]
Looks good!

**Comment by xmnlab** [comment]
thanks for the review @fccoelho

**Pull request merged**
