### PR TITLE
Fix coverage test

### PR DESCRIPTION
**Pull request by xmnlab**
## Description

This PR aims to fix 2 problems:

- it is missing BLAS library that pymc depends on
- coverage badge needs the the coverage data beforehand

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/thegraphnetwork/epigraphhub_py/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I've read the [`CONTRIBUTING.md`](https://github.com/thegraphnetwork/epigraphhub_py/blob/master/CONTRIBUTING.md) guide.
- [ ] I've updated the code style using `make codestyle`.
- [ ] I've written tests for all new methods and classes that I created.
- [ ] I've written the docstring in Google format for all the methods and classes that I used.

### CODE REVIEW

**Comment by xmnlab** [comment]
@fccoelho not sure if it is the way to go for this project, but it depends on BLAS and the easiest way to have it installed is using conda environment. in the conda environment file I pinned python there and added theano-pymc so it will automatically install the BLAS dependencies. also I added poetry, so it doesn't need to install it "manually".

for the test .. not sure why but, specifying the package name to `--cov` is not working ... so I just keep the flag with no value .. 
I saw that there is an "include" configuration for the coverage test .. but it seems it didn´t work with the previous command ... so I just keep the flag --cov with no value ... and locally the badge seems to be generated correctly

**Comment by xmnlab** [comment]
btw this was the error about BLAS: https://github.com/thegraphnetwork/epigraphhub_py/runs/4938788054?check_suite_focus=true#step:8:29

**Review by fccoelho — APPROVED** [review]
Seems ok to me

**Comment by fccoelho** [comment]
The package name is different from the repo name. maybe this is what was creting the problem?

**Pull request merged**
