### PR TITLE
[fix] Update poetry and pyproject to ngboost-release

### PR DESCRIPTION
**Pull request by eduardocorrearaujo**
## Description

Change ngboost to ngboost-release 

## Checklist

- [x] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/thegraphnetwork/epigraphhub_py/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I've read the [`CONTRIBUTING.md`](https://github.com/thegraphnetwork/epigraphhub_py/blob/master/CONTRIBUTING.md) guide.
- [x] I've used pre-commit hook locally.
- [x] I've written tests for all new methods and classes that I created.
- [ ] I've written the docstring in Google format for all the methods and classes that I used.
- [ ] Semantic-release prefix title used:
  - Use the prefix `chore(docs):` for Examples / docs / tutorials / dependencies update
  - Use the prefix `fix:` for a bug fix
    (non-breaking change which fixes an issue).
  - Use the prefix `chore(improvement):` for an improvement
    (non-breaking change which improves an existing feature).
  - Use the prefix `feat:` for a new feature
    (non-breaking change which adds functionality).
  - Use the prefix `breaking change:` for a breaking change
    (fix or feature that would cause existing functionality to change).
  - Use the prefix `chore(security):` for a security fix.

**Note**: The title prefix can be also expanded with more information
inside the parenthesis. Some examples for a full title (prefix + message):
- `fix(login): Fix the login page`.
- `feat(forecast): Add a weather forecast page`.
- `chore(security-login): Add a weather forecast page`.

### CODE REVIEW

**Comment by xmnlab** [comment]
@eduardocorrearaujo you need to remove also the current ngboost: https://github.com/thegraphnetwork/epigraphhub_py/pull/180/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R58

`poetry remove ngboost `

**Comment by xmnlab** [comment]
Maybe you would need to remove poetry lock and run again poetry install locally. Maybe there is already a command for that, maybe poetry lock .. but I am not sure

**Review by fccoelho — APPROVED** [review]

**Comment by xmnlab** [comment]
@eduardocorrearaujo what is the status of this PR?
do you need any help?

**Comment by eduardocorrearaujo** [comment]
> @eduardocorrearaujo what is the status of this PR? do you need any help?

Yes. I don't know why the build is falling. Before I do the commits, the install dependencies tests were passing, but an error was given in one of the tests of the `world_data_bank` script. 

Since this test was running on my local machine, I thought that could be a problem with the `wbgapi` version used. So, I typed `poetry add wbgapi==1.0.7` and did the commit, but after it, the code started to break again in the install dependencies tests.

**Comment by xmnlab** [comment]
ok I will take a look into that in a bit

**Comment by xmnlab** [comment]
thanks @eduardocorrearaujo for working on that!

**Pull request merged**
