### PR TITLE
[chore] removed docs folder

### LINKED ISSUE #175: Removing documentation  folder
Since we are maintaining the documentation on a [separate repo](https://github.com/thegraphnetwork/epigraphhub-lib-docs), we should delete the docs folder to avoid confusion.

### PR DESCRIPTION
**Pull request by fccoelho**
## Description

This removes the left over docs folder that has already been moved to the documentation project

## Related Issue
closes #175

### CODE REVIEW

**Comment by fccoelho** [comment]
@eduardocorrearaujo and @Anavelyz 
could you please review this PR?

**Comment by xmnlab** [comment]
there is a conflict with poetry. this branch needs a rebase on top of the main branch

**Comment by fccoelho** [comment]
> there is a conflict with poetry. this branch needs a rebase on top of the main branch

rebased.

**Comment by Anavelyz** [comment]
@xmnlab, @fccoelho here required a merge, I did it. As the poetry file was involved I ran the poetry lock command, now some more faults appeared. What do you recommend to correct this?

**Comment by xmnlab** [comment]
@Anavelyz is this the correct branch/PR for your changes? I am a bit lost here

**Comment by Anavelyz** [comment]
> @Anavelyz is this the correct branch/PR for your changes? I am a bit lost here

@fccoelho had asked me a while ago to review this PR, I recently noticed

**Comment by xmnlab** [comment]
ok, so maybe you could try to remove poetry.lock and run `poetry lock` to generate a brand new file.

**Pull request closed without merging**
